name: OctopiaCore
main: me.champ.octopia.Core
description: Core plugin for Octopia MC
version: 0.1
api-version: 1.12.2
depends: [Vault]
commands:
  oc:
    usage: /oc
  help:
    usage: /help
  ptset:
    usage: /ptset
  ptcheck:
    usage: /ptcheck
  ptreset:
    usage: /ptreset
  ocstats:
    usage: /ocstats
  ptleaderboard:
    usage: /ptleaderboard